### ISSUE TITLE
App is crashing in Samsung J5 Api 23.

### ISSUE THREAD

**Issue by SurendiranNK** [googlesamples/android-PdfRendererBasic#26]
08-02 10:39:22.468 6573-6573/com.example.android.pdfrendererbasic E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.example.android.pdfrendererbasic, PID: 6573
                                                                                    java.lang.IllegalStateException: Already closed
                                                                                        at android.graphics.pdf.PdfRenderer$Page.throwIfClosed(PdfRenderer.java:419)
                                                                                        at android.graphics.pdf.PdfRenderer$Page.close(PdfRenderer.java:394)
                                                                                        at com.example.android.pdfrendererbasic.PdfRendererBasicFragment.showPage(PdfRendererBasicFragment.java:197)
                                                                                        at com.example.android.pdfrendererbasic.PdfRendererBasicFragment.onStart(PdfRendererBasicFragment.java:122)
                                                                                        at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3186)
                                                                                        at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:203)
                                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:582)
                                                                                        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
                                                                                        at android.app.Activity.performStart(Activity.java:6943)
                                                                                        at android.app.Activity.performRestart(Activity.java:7002)
                                                                                        at android.app.ActivityThread.handleSleeping(ActivityThread.java:4942)
                                                                                        at android.app.ActivityThread.access$3600(ActivityThread.java:229)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-02 10:44:22.738 6573-6573/com.example.android.pdfrendererbasic I/Process: Sending signal. PID: 6573 SIG: 9

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
